import { z } from "zod";
import { conceptStatusList } from "../types/concept";
import type { Concept } from "../types/concept";
import type { ConceptSourceAnchor } from "../types/conceptSourceAnchor";
import type { ContextCard } from "../types/contextCard";
import type { LearningMaterial } from "../types/learningMaterial";
import type { QuizAttemptLog, QuizDeck, QuizQuestion } from "../types/quiz";
import type { ResearchReport } from "../types/researchReport";
import {
  conceptMediaRefSchema,
  quizDeckSchema,
  quizQuestionSchema,
  researchReportSchema
} from "../utils/conceptImportValidation";
import { conceptSourceAnchorSchema, learningMaterialSchema } from "../utils/learningMaterialImportValidation";
import { isValidImportedQuizAttemptLog, normalizeQuizAttemptLog } from "../utils/normalizeQuizAttemptLog";
import { normalizeDomainColorMap } from "../utils/domainColors";
import { normalizeThemeSettings } from "../theme/storage";
import { isSyncableSettingKey } from "./entityConfig";
import type { SyncableMediaMetadata, SyncableSettingPayload, SyncEntityType } from "./types";

const isoString = z.string().min(1).refine((value) => Number.isFinite(Date.parse(value)), {
  message: "ISO 日時文字列である必要があります"
});

const conceptSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  definition: z.string(),
  myInterpretation: z.string(),
  domainTags: z.array(z.string()),
  researchTags: z.array(z.string()),
  relatedIds: z.array(z.string()),
  prerequisiteIds: z.array(z.string()),
  media: z.array(conceptMediaRefSchema).optional(),
  source: z.object({
    book: z.string(),
    page: z.string(),
    author: z.string().nullable()
  }),
  notes: z.string(),
  status: z.enum(conceptStatusList),
  favorite: z.boolean(),
  createdAt: z.string().min(1),
  updatedAt: z.string().min(1),
  contextDefinitions: z
    .array(
      z.object({
        id: z.string().min(1),
        context: z.string(),
        definition: z.string()
      })
    )
    .optional(),
  sourceContextCardId: z.string().optional(),
  autoGenerated: z.boolean().optional(),
  sourceContextCardTermKey: z.string().optional()
});

const contextCardSchema = z.object({
  id: z.string().min(1),
  title: z.string(),
  domain: z.string().optional(),
  domainTags: z.array(z.string()),
  centralQuestion: z.string(),
  background: z.string(),
  flow: z.string(),
  keyConcepts: z.string(),
  linkedConcepts: z.array(z.string()),
  createdAt: z.string().min(1),
  updatedAt: z.string().min(1)
});

const mediaMetadataSchema = z.object({
  id: z.string().min(1),
  conceptId: z.string().min(1),
  kind: z.enum(["image", "video"]),
  mimeType: z.string().min(1),
  fileName: z.string().min(1),
  fileSize: z.number().finite().nonnegative(),
  caption: z.string().optional(),
  createdAt: z.string().min(1),
  updatedAt: z.string().min(1)
});

const settingPayloadSchema = z
  .object({
    key: z.string().min(1),
    value: z.unknown()
  })
  .superRefine((payload, ctx) => {
    if (!isSyncableSettingKey(payload.key)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "同期 allowlist に無い setting key です",
        path: ["key"]
      });
      return;
    }
    if (payload.key === "domainColors") {
      if (typeof payload.value !== "object" || payload.value === null || Array.isArray(payload.value)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "domainColors はオブジェクトである必要があります",
          path: ["value"]
        });
      }
      return;
    }
    if (payload.key === "themeSettings") {
      if (typeof payload.value !== "object" || payload.value === null || Array.isArray(payload.value)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "themeSettings はオブジェクトである必要があります",
          path: ["value"]
        });
      }
    }
  });

export const parseDomainPayload = (
  entityType: SyncEntityType,
  data: unknown
): { ok: true; value: unknown } | { ok: false; message: string } => {
  switch (entityType) {
    case "concept": {
      const parsed = conceptSchema.safeParse(data);
      return parsed.success
        ? { ok: true, value: parsed.data as Concept }
        : { ok: false, message: "concept data が不正です" };
    }
    case "contextCard": {
      const parsed = contextCardSchema.safeParse(data);
      return parsed.success
        ? { ok: true, value: parsed.data as ContextCard }
        : { ok: false, message: "contextCard data が不正です" };
    }
    case "quizQuestion": {
      const parsed = quizQuestionSchema.safeParse(data);
      return parsed.success
        ? { ok: true, value: parsed.data as QuizQuestion }
        : { ok: false, message: "quizQuestion data が不正です" };
    }
    case "quizDeck": {
      const parsed = quizDeckSchema.safeParse(data);
      return parsed.success
        ? { ok: true, value: parsed.data as QuizDeck }
        : { ok: false, message: "quizDeck data が不正です" };
    }
    case "quizAttemptLog": {
      if (typeof data !== "object" || data === null || Array.isArray(data)) {
        return { ok: false, message: "quizAttemptLog data が不正です" };
      }
      const normalized = normalizeQuizAttemptLog(data as Partial<QuizAttemptLog>);
      if (!isValidImportedQuizAttemptLog(normalized)) {
        return { ok: false, message: "quizAttemptLog data が不正です" };
      }
      return { ok: true, value: normalized };
    }
    case "researchReport": {
      const parsed = researchReportSchema.safeParse(data);
      return parsed.success
        ? { ok: true, value: parsed.data as ResearchReport }
        : { ok: false, message: "researchReport data が不正です" };
    }
    case "learningMaterial": {
      const parsed = learningMaterialSchema.safeParse(data);
      if (!parsed.success) {
        return { ok: false, message: "learningMaterial data が不正です" };
      }
      return { ok: true, value: parsed.data as LearningMaterial };
    }
    case "conceptSourceAnchor": {
      const parsed = conceptSourceAnchorSchema.safeParse(data);
      return parsed.success
        ? { ok: true, value: parsed.data as ConceptSourceAnchor }
        : { ok: false, message: "conceptSourceAnchor data が不正です" };
    }
    case "media": {
      const parsed = mediaMetadataSchema.safeParse(data);
      if (!parsed.success) {
        return { ok: false, message: "media metadata が不正です（Blob 本体は同期対象外）" };
      }
      if ("blob" in (data as object)) {
        return { ok: false, message: "media Blob 本体は Private Sync の対象外です" };
      }
      return { ok: true, value: parsed.data as SyncableMediaMetadata };
    }
    case "setting": {
      const parsed = settingPayloadSchema.safeParse(data);
      if (!parsed.success) {
        return { ok: false, message: "setting data が不正です" };
      }
      const key = parsed.data.key;
      if (!isSyncableSettingKey(key)) {
        return { ok: false, message: "setting key は同期 allowlist にありません" };
      }
      if (key === "domainColors") {
        const value = normalizeDomainColorMap(parsed.data.value);
        return { ok: true, value: { key, value } satisfies SyncableSettingPayload<"domainColors"> };
      }
      const value = normalizeThemeSettings(parsed.data.value);
      return { ok: true, value: { key, value } satisfies SyncableSettingPayload<"themeSettings"> };
    }
    default: {
      const _never: never = entityType;
      return { ok: false, message: `未対応の entityType: ${_never as string}` };
    }
  }
};

export const isIsoTimestamp = (value: unknown): value is string =>
  isoString.safeParse(value).success;
