import { describe, expect, it } from "vitest";
import { createEmptyConceptInput, type Concept } from "../../types/concept";
import { buildAIConceptSnapshot } from "./conceptSnapshot";

const concept = (overrides: Partial<Concept> = {}): Concept => ({
  ...createEmptyConceptInput(),
  id: "concept-1",
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-01-01T00:00:00.000Z",
  title: "自由意志",
  definition: "行為の原因を自らに帰属できること。",
  myInterpretation: "選択の経験として捉える。",
  notes: "非公開メモ",
  source: { book: "秘密の本", page: "12", author: "著者" },
  relatedIds: ["concept-2", "concept-3"],
  media: [{ id: "media-1", kind: "image", fileName: "a.png", sortOrder: 0 }],
  domainTags: ["哲学"],
  researchTags: ["研究"],
  favorite: true,
  status: "active",
  contextDefinitions: [{ id: "ctx-1", context: "倫理", definition: "文脈定義" }],
  sourceContextCardId: "card-secret",
  autoGenerated: true,
  ...overrides
});

describe("buildAIConceptSnapshot", () => {
  it("titleを取得できる", () => {
    expect(buildAIConceptSnapshot(concept()).title).toBe("自由意志");
  });

  it("definitionを取得できる", () => {
    expect(buildAIConceptSnapshot(concept()).definition).toBe("行為の原因を自らに帰属できること。");
  });

  it("空のdefinition / myInterpretationは省略する", () => {
    const snapshot = buildAIConceptSnapshot(concept({ definition: "  ", myInterpretation: "" }));
    expect(snapshot).not.toHaveProperty("definition");
    expect(snapshot).not.toHaveProperty("myInterpretation");
  });

  it("myInterpretationを取得できる", () => {
    expect(buildAIConceptSnapshot(concept()).myInterpretation).toBe("選択の経験として捉える。");
  });

  it("relatedTitlesを任意で追加できる", () => {
    expect(buildAIConceptSnapshot(concept(), { relatedTitles: ["決定論", " 両立論 "] }).relatedTitles).toEqual([
      "決定論",
      "両立論"
    ]);
  });

  it("空のrelatedTitlesは省略する", () => {
    expect(buildAIConceptSnapshot(concept(), { relatedTitles: ["  ", ""] })).not.toHaveProperty("relatedTitles");
    expect(buildAIConceptSnapshot(concept())).not.toHaveProperty("relatedTitles");
  });

  it("relatedIdsを含まない", () => {
    const snapshot = buildAIConceptSnapshot(concept(), { relatedTitles: ["決定論"] });
    expect(snapshot).not.toHaveProperty("relatedIds");
    expect(JSON.stringify(snapshot)).not.toContain("concept-2");
  });

  it("notesを含まない", () => {
    expect(buildAIConceptSnapshot(concept())).not.toHaveProperty("notes");
    expect(JSON.stringify(buildAIConceptSnapshot(concept()))).not.toContain("非公開メモ");
  });

  it("mediaを含まない", () => {
    expect(buildAIConceptSnapshot(concept())).not.toHaveProperty("media");
    expect(JSON.stringify(buildAIConceptSnapshot(concept()))).not.toContain("media-1");
  });

  it("sourceを含まない", () => {
    const snapshot = buildAIConceptSnapshot(concept());
    expect(snapshot).not.toHaveProperty("source");
    expect(snapshot).not.toHaveProperty("domainTags");
    expect(snapshot).not.toHaveProperty("researchTags");
    expect(snapshot).not.toHaveProperty("contextDefinitions");
    expect(snapshot).not.toHaveProperty("favorite");
    expect(snapshot).not.toHaveProperty("status");
    expect(snapshot).not.toHaveProperty("createdAt");
    expect(snapshot).not.toHaveProperty("updatedAt");
    expect(snapshot).not.toHaveProperty("sourceContextCardId");
    expect(snapshot).not.toHaveProperty("autoGenerated");
    expect(JSON.stringify(snapshot)).not.toContain("秘密の本");
    expect(JSON.stringify(snapshot)).not.toContain("card-secret");
  });

  it("元Conceptを変更しない", () => {
    const item = concept();
    const before = structuredClone(item);
    buildAIConceptSnapshot(item, { relatedTitles: ["決定論"] });
    expect(item).toEqual(before);
  });
});
