import {
  createEmptyConceptInput,
  type Concept,
  type ConceptInput
} from "../types/concept";
import type { ContextCard } from "../types/contextCard";
import { parseBulkRelatedConceptTitles } from "./bulkRelatedConcepts";
import { normalizeConceptTitle } from "./normalizeConceptTitle";

/** keyConcepts 文字列から重要語句を抽出（trim・空除外・正規化タイトルでの重複除外） */
export function extractImportantTerms(keyConcepts: string): string[] {
  const parts = parseBulkRelatedConceptTitles(keyConcepts);
  const seen = new Set<string>();
  const out: string[] = [];

  for (const term of parts) {
    const trimmed = term.trim();
    const normalized = normalizeConceptTitle(trimmed);
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    out.push(trimmed);
  }

  return out;
}

/** 既存概念タイトルの照合用キー集合（正規化タイトル） */
export function buildExistingConceptTitleKeys(concepts: Concept[]): Set<string> {
  const keys = new Set<string>();
  for (const concept of concepts) {
    const key = normalizeConceptTitle(concept.title);
    if (key) {
      keys.add(key);
    }
  }
  return keys;
}

export function mergeDomainTags(existingTags: string[], incomingTags: string[]): string[] {
  const seen = new Set<string>();
  const merged: string[] = [];

  const append = (tag: string) => {
    const trimmed = tag.trim();
    if (!trimmed) {
      return;
    }
    const key = trimmed.toLowerCase();
    if (seen.has(key)) {
      return;
    }
    seen.add(key);
    merged.push(trimmed);
  };

  for (const tag of existingTags) {
    append(tag);
  }
  for (const tag of incomingTags) {
    append(tag);
  }

  return merged;
}

export function findConceptsByTitle(concepts: Concept[], term: string): Concept[] {
  const normalizedTerm = normalizeConceptTitle(term);
  if (!normalizedTerm) {
    return [];
  }
  return concepts.filter(
    (concept) => normalizeConceptTitle(concept.title) === normalizedTerm
  );
}

const sourceTermKeyOf = (concept: Concept): string =>
  normalizeConceptTitle(concept.sourceContextCardTermKey ?? "");

const isAutoGeneratedFromCard = (concept: Concept, contextCardId: string): boolean =>
  concept.autoGenerated === true && concept.sourceContextCardId === contextCardId;

const isLegacySourceCandidate = (concept: Concept, contextCardId: string): boolean =>
  isAutoGeneratedFromCard(concept, contextCardId) && !sourceTermKeyOf(concept);

export function createAutoGeneratedConceptInput(
  title: string,
  domainTags: string[],
  sourceContextCardId: string
): ConceptInput {
  return {
    ...createEmptyConceptInput(),
    title,
    definition: "",
    domainTags: [...domainTags],
    status: "draft",
    sourceContextCardId,
    autoGenerated: true,
    sourceContextCardTermKey: normalizeConceptTitle(title)
  };
}

export type ConceptSyncUpdate = {
  conceptId: string;
  updates: Partial<Pick<ConceptInput, "domainTags" | "sourceContextCardTermKey">>;
  domainTagsChanged: boolean;
  provenanceChanged: boolean;
};

/** @deprecated ConceptSyncUpdate を使用してください */
export type ConceptTagUpdate = {
  conceptId: string;
  domainTags: string[];
};

export type ConceptSyncPlan = {
  conceptsToCreate: ConceptInput[];
  conceptsToUpdate: ConceptSyncUpdate[];
};

export function computeConceptSyncPlan(
  contextCard: ContextCard,
  existingConcepts: Concept[]
): ConceptSyncPlan {
  const terms = extractImportantTerms(contextCard.keyConcepts);
  const incomingTags = (contextCard.domainTags ?? [])
    .map((tag) => tag.trim())
    .filter(Boolean);
  const currentTermKeys = new Set(
    terms.map((term) => normalizeConceptTitle(term)).filter(Boolean)
  );

  const conceptsToCreate: ConceptInput[] = [];
  const pendingCreateKeys = new Set<string>();
  const planned = new Map<
    string,
    Partial<Pick<ConceptInput, "domainTags" | "sourceContextCardTermKey">>
  >();

  const schedule = (
    concept: Concept,
    options: { mergeTags: boolean; provenanceKey?: string }
  ) => {
    const existingPlan = planned.get(concept.id) ?? {};
    const updates: Partial<Pick<ConceptInput, "domainTags" | "sourceContextCardTermKey">> = {
      ...existingPlan
    };

    if (options.mergeTags && incomingTags.length > 0) {
      const baseTags = existingPlan.domainTags ?? concept.domainTags ?? [];
      const merged = mergeDomainTags(baseTags, contextCard.domainTags);
      if (merged.length !== (concept.domainTags ?? []).length) {
        updates.domainTags = merged;
      }
    }

    if (options.provenanceKey) {
      const plannedKey = existingPlan.sourceContextCardTermKey
        ? normalizeConceptTitle(existingPlan.sourceContextCardTermKey)
        : sourceTermKeyOf(concept);
      if (plannedKey !== options.provenanceKey) {
        updates.sourceContextCardTermKey = options.provenanceKey;
      }
    }

    if (updates.domainTags !== undefined || updates.sourceContextCardTermKey !== undefined) {
      planned.set(concept.id, updates);
    }
  };

  const resolvedTermKeys = new Set<string>();
  const ambiguousTermKeys = new Set<string>();
  const usedLegacyIds = new Set<string>();

  for (const term of terms) {
    const termKey = normalizeConceptTitle(term);
    const provenanceMatches = existingConcepts.filter(
      (concept) =>
        isAutoGeneratedFromCard(concept, contextCard.id) && sourceTermKeyOf(concept) === termKey
    );

    if (provenanceMatches.length === 1) {
      resolvedTermKeys.add(termKey);
      schedule(provenanceMatches[0], { mergeTags: true });
      continue;
    }

    if (provenanceMatches.length > 1) {
      ambiguousTermKeys.add(termKey);
      continue;
    }

    const legacyTitleMatches = existingConcepts.filter(
      (concept) =>
        isLegacySourceCandidate(concept, contextCard.id) &&
        normalizeConceptTitle(concept.title) === termKey
    );

    if (legacyTitleMatches.length === 1) {
      const onlyLegacy = legacyTitleMatches[0];
      resolvedTermKeys.add(termKey);
      usedLegacyIds.add(onlyLegacy.id);
      schedule(onlyLegacy, { mergeTags: true, provenanceKey: termKey });
      continue;
    }

    if (legacyTitleMatches.length > 1) {
      ambiguousTermKeys.add(termKey);
    }
  }

  const unresolvedTerms = terms.filter((term) => {
    const termKey = normalizeConceptTitle(term);
    return !resolvedTermKeys.has(termKey) && !ambiguousTermKeys.has(termKey);
  });
  const leftoverLegacy = existingConcepts.filter(
    (concept) =>
      isLegacySourceCandidate(concept, contextCard.id) && !usedLegacyIds.has(concept.id)
  );

  if (unresolvedTerms.length === 1 && leftoverLegacy.length === 1) {
    const term = unresolvedTerms[0];
    const termKey = normalizeConceptTitle(term);
    const onlyLegacy = leftoverLegacy[0];
    usedLegacyIds.add(onlyLegacy.id);
    resolvedTermKeys.add(termKey);
    schedule(onlyLegacy, { mergeTags: true, provenanceKey: termKey });
  }

  for (const term of terms) {
    const termKey = normalizeConceptTitle(term);
    if (resolvedTermKeys.has(termKey) || ambiguousTermKeys.has(termKey)) {
      continue;
    }

    const matchedConcepts = findConceptsByTitle(existingConcepts, term);

    if (matchedConcepts.length === 0) {
      if (pendingCreateKeys.has(termKey)) {
        continue;
      }
      pendingCreateKeys.add(termKey);
      conceptsToCreate.push(
        createAutoGeneratedConceptInput(term, contextCard.domainTags, contextCard.id)
      );
      continue;
    }

    if (matchedConcepts.length === 1) {
      const only = matchedConcepts[0];
      const existingKey = sourceTermKeyOf(only);
      const canReassignProvenance =
        isAutoGeneratedFromCard(only, contextCard.id) &&
        Boolean(existingKey) &&
        existingKey !== termKey &&
        !currentTermKeys.has(existingKey);

      schedule(only, {
        mergeTags: true,
        provenanceKey: canReassignProvenance ? termKey : undefined
      });
      continue;
    }

    // title match が複数: 誤更新・新規作成を避けて silent skip
  }

  return {
    conceptsToCreate,
    conceptsToUpdate: [...planned.entries()].map(([conceptId, updates]) => ({
      conceptId,
      updates,
      domainTagsChanged: updates.domainTags !== undefined,
      provenanceChanged: updates.sourceContextCardTermKey !== undefined
    }))
  };
}

/** @deprecated computeConceptSyncPlan の conceptsToCreate を返す互換ラッパー */
export function computeMissingConceptInputs(
  contextCard: ContextCard,
  existingConcepts: Concept[]
): ConceptInput[] {
  return computeConceptSyncPlan(contextCard, existingConcepts).conceptsToCreate;
}

export function formatSyncImportantTermsToast(
  createdCount: number,
  updatedCount: number
): string | null {
  if (createdCount > 0 && updatedCount > 0) {
    return `${createdCount}件の概念を自動生成し、${updatedCount}件の既存概念に分野タグを追加しました`;
  }
  if (createdCount > 0) {
    return `${createdCount}件の概念を自動生成しました`;
  }
  if (updatedCount > 0) {
    return `${updatedCount}件の既存概念に分野タグを追加しました`;
  }
  return null;
}
