import {
  createEmptyConceptInput,
  type Concept,
  type ConceptInput
} from "../types/concept";
import type { ContextCard } from "../types/contextCard";
import { parseBulkRelatedConceptTitles } from "./bulkRelatedConcepts";

/** keyConcepts 文字列から重要語句を抽出（trim・空除外・大文字小文字を無視した重複除外） */
export function extractImportantTerms(keyConcepts: string): string[] {
  const parts = parseBulkRelatedConceptTitles(keyConcepts);
  const seen = new Set<string>();
  const out: string[] = [];

  for (const term of parts) {
    const trimmed = term.trim();
    const normalized = trimmed.toLowerCase();
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    out.push(trimmed);
  }

  return out;
}

/** 既存概念タイトルの照合用キー集合（trim + 小文字化） */
export function buildExistingConceptTitleKeys(concepts: Concept[]): Set<string> {
  const keys = new Set<string>();
  for (const concept of concepts) {
    const key = concept.title.trim().toLowerCase();
    if (key) {
      keys.add(key);
    }
  }
  return keys;
}

export function mergeDomainTags(existingTags: string[], incomingTags: string[]): string[] {
  const seen = new Set<string>();
  const merged: string[] = [];

  const append = (tag: string) => {
    const trimmed = tag.trim();
    if (!trimmed) {
      return;
    }
    const key = trimmed.toLowerCase();
    if (seen.has(key)) {
      return;
    }
    seen.add(key);
    merged.push(trimmed);
  };

  for (const tag of existingTags) {
    append(tag);
  }
  for (const tag of incomingTags) {
    append(tag);
  }

  return merged;
}

export function findConceptsByTitle(concepts: Concept[], term: string): Concept[] {
  const normalizedTerm = term.trim().toLowerCase();
  if (!normalizedTerm) {
    return [];
  }
  return concepts.filter(
    (concept) => concept.title.trim().toLowerCase() === normalizedTerm
  );
}

export function createAutoGeneratedConceptInput(
  title: string,
  domainTags: string[],
  sourceContextCardId: string
): ConceptInput {
  return {
    ...createEmptyConceptInput(),
    title,
    definition: "",
    domainTags: [...domainTags],
    status: "draft",
    sourceContextCardId,
    autoGenerated: true
  };
}

export type ConceptTagUpdate = {
  conceptId: string;
  domainTags: string[];
};

export type ConceptSyncPlan = {
  conceptsToCreate: ConceptInput[];
  conceptsToUpdate: ConceptTagUpdate[];
};

export function computeConceptSyncPlan(
  contextCard: ContextCard,
  existingConcepts: Concept[]
): ConceptSyncPlan {
  const terms = extractImportantTerms(contextCard.keyConcepts);
  const incomingTags = (contextCard.domainTags ?? [])
    .map((tag) => tag.trim())
    .filter(Boolean);

  const conceptsToCreate: ConceptInput[] = [];
  const pendingCreateKeys = new Set<string>();
  const updatePlanned = new Map<string, string[]>();

  for (const term of terms) {
    const matchedConcepts = findConceptsByTitle(existingConcepts, term);

    if (matchedConcepts.length === 0) {
      const key = term.toLowerCase();
      if (pendingCreateKeys.has(key)) {
        continue;
      }
      pendingCreateKeys.add(key);
      conceptsToCreate.push(
        createAutoGeneratedConceptInput(term, contextCard.domainTags, contextCard.id)
      );
      continue;
    }

    if (incomingTags.length === 0) {
      continue;
    }

    for (const concept of matchedConcepts) {
      const baseTags = updatePlanned.get(concept.id) ?? concept.domainTags ?? [];
      const merged = mergeDomainTags(baseTags, contextCard.domainTags);
      const originalLength = (concept.domainTags ?? []).length;
      if (merged.length !== originalLength) {
        updatePlanned.set(concept.id, merged);
      }
    }
  }

  return {
    conceptsToCreate,
    conceptsToUpdate: [...updatePlanned.entries()].map(([conceptId, domainTags]) => ({
      conceptId,
      domainTags
    }))
  };
}

/** @deprecated computeConceptSyncPlan の conceptsToCreate を返す互換ラッパー */
export function computeMissingConceptInputs(
  contextCard: ContextCard,
  existingConcepts: Concept[]
): ConceptInput[] {
  return computeConceptSyncPlan(contextCard, existingConcepts).conceptsToCreate;
}

export type SyncImportantTermsResult = {
  createdConcepts: Concept[];
  createdCount: number;
  updatedCount: number;
};

export function formatSyncImportantTermsToast(
  createdCount: number,
  updatedCount: number
): string | null {
  if (createdCount > 0 && updatedCount > 0) {
    return `${createdCount}件の概念を自動生成し、${updatedCount}件の既存概念に分野タグを追加しました`;
  }
  if (createdCount > 0) {
    return `${createdCount}件の概念を自動生成しました`;
  }
  if (updatedCount > 0) {
    return `${updatedCount}件の既存概念に分野タグを追加しました`;
  }
  return null;
}

/**
 * 文脈カードの重要概念（keyConcepts）を既存 concepts と同期する。
 * 未登録語句は新規作成、同名概念には不足分野タグのみ追加する。
 */
export async function syncImportantTermsToConcepts(
  contextCard: ContextCard,
  existingConcepts: Concept[],
  handlers: {
    createConcept: (input: ConceptInput) => Promise<Concept>;
    updateConcept: (
      id: string,
      updates: Partial<ConceptInput>
    ) => Promise<Concept | undefined>;
  }
): Promise<SyncImportantTermsResult> {
  const plan = computeConceptSyncPlan(contextCard, existingConcepts);
  const createdConcepts: Concept[] = [];
  let updatedCount = 0;

  for (const input of plan.conceptsToCreate) {
    try {
      const created = await handlers.createConcept(input);
      createdConcepts.push(created);
    } catch (error) {
      console.error(`概念の自動生成に失敗しました: ${input.title}`, error);
    }
  }

  for (const update of plan.conceptsToUpdate) {
    try {
      const updated = await handlers.updateConcept(update.conceptId, {
        domainTags: update.domainTags
      });
      if (updated) {
        updatedCount += 1;
      }
    } catch (error) {
      console.error(
        `既存概念への分野タグ追加に失敗しました: ${update.conceptId}`,
        error
      );
    }
  }

  return {
    createdConcepts,
    createdCount: createdConcepts.length,
    updatedCount
  };
}
