import {
  createEmptyConceptInput,
  type Concept,
  type ConceptInput
} from "../types/concept";
import type { ContextCard } from "../types/contextCard";
import { parseBulkRelatedConceptTitles } from "./bulkRelatedConcepts";

/** keyConcepts 文字列から重要語句を抽出（trim・空除外・大文字小文字を無視した重複除外） */
export function extractImportantTerms(keyConcepts: string): string[] {
  const parts = parseBulkRelatedConceptTitles(keyConcepts);
  const seen = new Set<string>();
  const out: string[] = [];

  for (const term of parts) {
    const trimmed = term.trim();
    const normalized = trimmed.toLowerCase();
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    out.push(trimmed);
  }

  return out;
}

/** 既存概念タイトルの照合用キー集合（trim + 小文字化） */
export function buildExistingConceptTitleKeys(concepts: Concept[]): Set<string> {
  const keys = new Set<string>();
  for (const concept of concepts) {
    const key = concept.title.trim().toLowerCase();
    if (key) {
      keys.add(key);
    }
  }
  return keys;
}

export function createAutoGeneratedConceptInput(
  title: string,
  domainTags: string[],
  sourceContextCardId: string
): ConceptInput {
  return {
    ...createEmptyConceptInput(),
    title,
    definition: "",
    domainTags: [...domainTags],
    status: "draft",
    sourceContextCardId,
    autoGenerated: true
  };
}

/** 未登録の重要語句に対応する ConceptInput 一覧を算出する（永続化はしない） */
export function computeMissingConceptInputs(
  contextCard: ContextCard,
  existingConcepts: Concept[]
): ConceptInput[] {
  const terms = extractImportantTerms(contextCard.keyConcepts);
  if (terms.length === 0) {
    return [];
  }

  const existingKeys = buildExistingConceptTitleKeys(existingConcepts);
  const pendingKeys = new Set(existingKeys);
  const inputs: ConceptInput[] = [];

  for (const term of terms) {
    const key = term.toLowerCase();
    if (pendingKeys.has(key)) {
      continue;
    }
    pendingKeys.add(key);
    inputs.push(
      createAutoGeneratedConceptInput(term, contextCard.domainTags, contextCard.id)
    );
  }

  return inputs;
}

export type SyncImportantTermsResult = {
  createdConcepts: Concept[];
  createdCount: number;
};

/**
 * 文脈カードの重要概念（keyConcepts）を既存 concepts と照合し、
 * 未登録語句のみ新規概念として作成する。既存概念は変更しない。
 */
export async function syncImportantTermsToConcepts(
  contextCard: ContextCard,
  existingConcepts: Concept[],
  createConcept: (input: ConceptInput) => Promise<Concept>
): Promise<SyncImportantTermsResult> {
  const inputs = computeMissingConceptInputs(contextCard, existingConcepts);
  const createdConcepts: Concept[] = [];

  for (const input of inputs) {
    try {
      const created = await createConcept(input);
      createdConcepts.push(created);
    } catch (error) {
      console.error(`概念の自動生成に失敗しました: ${input.title}`, error);
    }
  }

  return { createdConcepts, createdCount: createdConcepts.length };
}
