import { describe, expect, it } from "vitest";
import { createEmptyConceptInput, type Concept } from "../types/concept";
import type { ContextCard } from "../types/contextCard";
import { sanitizeConcept } from "../storage/indexeddb";
import { validateBackupImportPayload } from "./conceptImportValidation";
import {
  computeConceptSyncPlan,
  createAutoGeneratedConceptInput,
  formatSyncImportantTermsToast
} from "./syncImportantTermsToConcepts";

const iso = "2026-01-01T00:00:00.000Z";

const card = (overrides: Partial<ContextCard> = {}): ContextCard => ({
  id: "card-1",
  title: "カード",
  domainTags: ["情報"],
  centralQuestion: "",
  background: "",
  flow: "",
  keyConcepts: "AI",
  linkedConcepts: [],
  createdAt: iso,
  updatedAt: iso,
  ...overrides
});

const concept = (overrides: Partial<Concept> = {}): Concept => ({
  ...createEmptyConceptInput(),
  id: "A",
  title: "AI",
  createdAt: iso,
  updatedAt: iso,
  ...overrides
});

const canonicalImportConcept = (overrides: Record<string, unknown> = {}) => ({
  id: "A",
  title: "AI",
  definition: "",
  myInterpretation: "",
  domainTags: [] as string[],
  researchTags: [] as string[],
  relatedIds: [] as string[],
  source: { book: "", page: "", author: null },
  notes: "",
  status: "draft" as const,
  favorite: false,
  createdAt: iso,
  updatedAt: iso,
  ...overrides
});

describe("createAutoGeneratedConceptInput", () => {
  it("新規生成時に sourceContextCardId / autoGenerated / term identity を保存する", () => {
    const input = createAutoGeneratedConceptInput("AI", ["情報"], "card-1");
    expect(input.sourceContextCardId).toBe("card-1");
    expect(input.autoGenerated).toBe(true);
    expect(input.sourceContextCardTermKey).toBe("ai");
    expect(input.title).toBe("AI");
  });
});

describe("computeConceptSyncPlan provenance identity (#194)", () => {
  it("ContextCard の term から生成する input に term identity を付ける", () => {
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI" }), []);
    expect(plan.conceptsToCreate).toHaveLength(1);
    expect(plan.conceptsToCreate[0]?.sourceContextCardId).toBe("card-1");
    expect(plan.conceptsToCreate[0]?.autoGenerated).toBe(true);
    expect(plan.conceptsToCreate[0]?.sourceContextCardTermKey).toBe("ai");
  });

  it("rename 後の再同期で旧語句名 Concept を重複生成せず title も戻さない", () => {
    const renamed = concept({
      id: "A",
      title: "人工知能",
      definition: "ユーザー定義",
      sourceContextCardId: "card-1",
      autoGenerated: true,
      sourceContextCardTermKey: "ai"
    });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI" }), [renamed]);
    expect(plan.conceptsToCreate).toHaveLength(0);
    expect(plan.conceptsToUpdate.every((update) => !("title" in update.updates))).toBe(true);
    expect(plan.conceptsToUpdate.every((update) => !("definition" in update.updates))).toBe(
      true
    );
  });

  it("ユーザー編集済み title / definition を上書きしない", () => {
    const edited = concept({
      id: "A",
      title: "人工知能",
      definition: "ユーザー定義",
      domainTags: ["情報"],
      sourceContextCardId: "card-1",
      autoGenerated: true,
      sourceContextCardTermKey: "ai"
    });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["情報"] }), [
      edited
    ]);
    for (const update of plan.conceptsToUpdate) {
      expect(update.updates).not.toHaveProperty("title");
      expect(update.updates).not.toHaveProperty("definition");
    }
  });

  it("unrelated な同名 Concept より provenance を優先し、U の domainTags は変えない", () => {
    const generated = concept({
      id: "A",
      title: "人工知能",
      domainTags: ["情報"],
      sourceContextCardId: "card-1",
      autoGenerated: true,
      sourceContextCardTermKey: "ai"
    });
    const unrelated = concept({
      id: "U",
      title: "AI",
      domainTags: ["別分野"],
      sourceContextCardId: undefined
    });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["情報", "ML"] }), [
      generated,
      unrelated
    ]);

    expect(plan.conceptsToCreate).toHaveLength(0);
    expect(plan.conceptsToUpdate.some((update) => update.conceptId === "U")).toBe(false);
    const generatedUpdate = plan.conceptsToUpdate.find((update) => update.conceptId === "A");
    expect(generatedUpdate?.updates.domainTags).toEqual(["情報", "ML"]);
  });

  it("keyConcepts 自体の変更は新しい source term として扱い、旧 Concept を付け替えない", () => {
    const original = concept({
      id: "A",
      title: "AI",
      sourceContextCardId: "card-1",
      autoGenerated: true,
      sourceContextCardTermKey: "ai"
    });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "人工知能" }), [original]);

    expect(plan.conceptsToCreate).toHaveLength(1);
    expect(plan.conceptsToCreate[0]?.title).toBe("人工知能");
    expect(plan.conceptsToCreate[0]?.sourceContextCardTermKey).toBe("人工知能");
    expect(
      plan.conceptsToUpdate.some(
        (update) =>
          update.conceptId === "A" && update.updates.sourceContextCardTermKey === "人工知能"
      )
    ).toBe(false);
    expect(plan.conceptsToUpdate.every((update) => !("title" in update.updates))).toBe(true);
  });

  it("legacy で title が term と一致すれば新規作成せず termKey を補完する", () => {
    const legacy = concept({
      id: "A",
      title: "AI",
      domainTags: ["情報"],
      sourceContextCardId: "card-1",
      autoGenerated: true
    });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI" }), [legacy]);
    expect(plan.conceptsToCreate).toHaveLength(0);
    expect(plan.conceptsToUpdate).toEqual([
      expect.objectContaining({
        conceptId: "A",
        provenanceChanged: true,
        updates: { sourceContextCardTermKey: "ai" }
      })
    ]);
  });

  it("legacy rename が一意なら新規作成せず termKey を補完する", () => {
    const legacy = concept({
      id: "A",
      title: "人工知能",
      domainTags: ["情報"],
      sourceContextCardId: "card-1",
      autoGenerated: true
    });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI" }), [legacy]);
    expect(plan.conceptsToCreate).toHaveLength(0);
    expect(plan.conceptsToUpdate).toEqual([
      expect.objectContaining({
        conceptId: "A",
        provenanceChanged: true,
        updates: { sourceContextCardTermKey: "ai" }
      })
    ]);
  });

  it("legacy が複数かつ unresolved term も複数なら配列順で対応付けない", () => {
    const legacyA = concept({
      id: "A",
      title: "人工知能",
      sourceContextCardId: "card-1",
      autoGenerated: true,
      updatedAt: "2026-02-01T00:00:00.000Z"
    });
    const legacyB = concept({
      id: "B",
      title: "機械学習",
      sourceContextCardId: "card-1",
      autoGenerated: true,
      updatedAt: "2026-03-01T00:00:00.000Z"
    });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI, ML" }), [legacyA, legacyB]);
    expect(plan.conceptsToCreate.map((input) => input.title)).toEqual(["AI", "ML"]);
    expect(
      plan.conceptsToUpdate.some((update) => update.updates.sourceContextCardTermKey)
    ).toBe(false);
  });

  it("既存の title 一致 Concept は従来どおり再利用し autoGenerated 化しない", () => {
    const existing = concept({
      id: "U",
      title: "AI",
      domainTags: ["情報"]
    });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["情報"] }), [
      existing
    ]);
    expect(plan.conceptsToCreate).toHaveLength(0);
    expect(plan.conceptsToUpdate).toHaveLength(0);
  });

  it("Concept rename と keyConcept 変更が同時で title が一意なら再利用する", () => {
    const renamed = concept({
      id: "A",
      title: "人工知能",
      sourceContextCardId: "card-1",
      autoGenerated: true,
      sourceContextCardTermKey: "ai"
    });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "人工知能" }), [renamed]);
    expect(plan.conceptsToCreate).toHaveLength(0);
    const update = plan.conceptsToUpdate.find((item) => item.conceptId === "A");
    expect(update?.updates.sourceContextCardTermKey).toBe("人工知能");
    expect(update?.updates).not.toHaveProperty("title");
  });

  it("provenance のみの補完は toast 用 updatedCount に載せない", () => {
    expect(formatSyncImportantTermsToast(0, 0)).toBeNull();
    expect(formatSyncImportantTermsToast(1, 0)).toBe("1件の概念を自動生成しました");
  });
});

describe("sourceContextCardTermKey persistence", () => {
  it("IndexedDB sanitize で field を保持する", () => {
    const { concept: normalized } = sanitizeConcept({
      id: "A",
      title: "人工知能",
      sourceContextCardId: "card-1",
      autoGenerated: true,
      sourceContextCardTermKey: "ai"
    });
    expect(normalized.sourceContextCardTermKey).toBe("ai");
    expect(normalized.sourceContextCardId).toBe("card-1");
    expect(normalized.autoGenerated).toBe(true);
  });

  it("field が無い既存レコードも読み込める", () => {
    const { concept: normalized } = sanitizeConcept({
      id: "A",
      title: "AI",
      sourceContextCardId: "card-1",
      autoGenerated: true
    });
    expect(normalized.sourceContextCardTermKey).toBeUndefined();
  });

  it("import validation で optional field を保持し、無い backup も読める", () => {
    const withField = validateBackupImportPayload({
      concepts: [
        canonicalImportConcept({
          sourceContextCardId: "card-1",
          autoGenerated: true,
          sourceContextCardTermKey: "ai"
        })
      ]
    });
    expect(withField.success).toBe(true);
    if (withField.success) {
      expect(withField.concepts[0]?.sourceContextCardTermKey).toBe("ai");
    }

    const withoutField = validateBackupImportPayload({
      concepts: [canonicalImportConcept({ title: "AI" })]
    });
    expect(withoutField.success).toBe(true);
    if (withoutField.success) {
      expect(withoutField.concepts[0]?.sourceContextCardTermKey).toBeUndefined();
    }
  });
});

describe("computeConceptSyncPlan title ambiguity (#195)", () => {
  const expectNoAutoChange = (plan: ReturnType<typeof computeConceptSyncPlan>) => {
    expect(plan.conceptsToCreate).toHaveLength(0);
    expect(plan.conceptsToUpdate).toHaveLength(0);
  };

  it("同名 Concept が2件なら domainTags を全件更新せず新規作成もしない", () => {
    const a1 = concept({ id: "A1", title: "AI", domainTags: ["情報"] });
    const a2 = concept({ id: "A2", title: "AI", domainTags: ["哲学"] });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["教育"] }), [
      a1,
      a2
    ]);
    expectNoAutoChange(plan);
    expect(plan.conceptsToUpdate.some((update) => update.conceptId === "A1")).toBe(false);
    expect(plan.conceptsToUpdate.some((update) => update.conceptId === "A2")).toBe(false);
  });

  it("title が一意なら不足 domainTags を追加する", () => {
    const only = concept({ id: "A", title: "AI", domainTags: ["情報"] });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["教育"] }), [
      only
    ]);
    expect(plan.conceptsToCreate).toHaveLength(0);
    expect(plan.conceptsToUpdate).toEqual([
      expect.objectContaining({
        conceptId: "A",
        domainTagsChanged: true,
        updates: { domainTags: ["情報", "教育"] }
      })
    ]);
  });

  it("正規化一致の同名も ambiguous として扱う", () => {
    const a1 = concept({ id: "A1", title: "AI", domainTags: ["情報"] });
    const a2 = concept({ id: "A2", title: "ＡＩ ", domainTags: ["哲学"] });
    const plan = computeConceptSyncPlan(card({ keyConcepts: " ai ", domainTags: ["教育"] }), [
      a1,
      a2
    ]);
    expectNoAutoChange(plan);
  });

  it("配列順を逆にしても create / update しない", () => {
    const a1 = concept({ id: "A1", title: "AI", domainTags: ["情報"] });
    const a2 = concept({ id: "A2", title: "AI", domainTags: ["哲学"] });
    expectNoAutoChange(
      computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["教育"] }), [a1, a2])
    );
    expectNoAutoChange(
      computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["教育"] }), [a2, a1])
    );
  });

  it("updatedAt を入れ替えても create / update しない", () => {
    const older = "2026-01-01T00:00:00.000Z";
    const newer = "2026-06-01T00:00:00.000Z";
    const a1Older = concept({
      id: "A1",
      title: "AI",
      domainTags: ["情報"],
      updatedAt: older
    });
    const a2Newer = concept({
      id: "A2",
      title: "AI",
      domainTags: ["哲学"],
      updatedAt: newer
    });
    const a1Newer = concept({
      id: "A1",
      title: "AI",
      domainTags: ["情報"],
      updatedAt: newer
    });
    const a2Older = concept({
      id: "A2",
      title: "AI",
      domainTags: ["哲学"],
      updatedAt: older
    });
    expectNoAutoChange(
      computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["教育"] }), [
        a1Older,
        a2Newer
      ])
    );
    expectNoAutoChange(
      computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["教育"] }), [
        a1Newer,
        a2Older
      ])
    );
  });

  it("legacy title match が複数なら termKey / domainTags を全件 backfill しない", () => {
    const l1 = concept({
      id: "L1",
      title: "AI",
      domainTags: ["情報"],
      sourceContextCardId: "card-1",
      autoGenerated: true
    });
    const l2 = concept({
      id: "L2",
      title: "ＡＩ",
      domainTags: ["哲学"],
      sourceContextCardId: "card-1",
      autoGenerated: true
    });
    const plan = computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["教育"] }), [
      l1,
      l2
    ]);
    expectNoAutoChange(plan);
    expect(
      plan.conceptsToUpdate.some((update) => update.updates.sourceContextCardTermKey)
    ).toBe(false);
  });

  it("exact provenance が重複していれば誰も更新せず新規生成もしない", () => {
    const p1 = concept({
      id: "P1",
      title: "人工知能",
      domainTags: ["情報"],
      sourceContextCardId: "card-1",
      autoGenerated: true,
      sourceContextCardTermKey: "ai"
    });
    const p2 = concept({
      id: "P2",
      title: "AI",
      domainTags: ["哲学"],
      sourceContextCardId: "card-1",
      autoGenerated: true,
      sourceContextCardTermKey: "ai"
    });
    expectNoAutoChange(
      computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: ["教育"] }), [p1, p2])
    );
  });

  it("incomingTags が空でも ambiguous から新規 Concept を作らない", () => {
    const a1 = concept({ id: "A1", title: "AI", domainTags: ["情報"] });
    const a2 = concept({ id: "A2", title: "AI", domainTags: ["哲学"] });
    expectNoAutoChange(
      computeConceptSyncPlan(card({ keyConcepts: "AI", domainTags: [] }), [a1, a2])
    );
  });
});
