import "fake-indexeddb/auto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { createEmptyConceptInput } from "../types/concept";
import { createEmptyContextCardInput, type ContextCardInput } from "../types/contextCard";
import { ContextCardIndexedDBStorage, IndexedDBStorage } from "./indexeddb";

const deleteDb = (): Promise<void> =>
  new Promise((resolve, reject) => {
    const request = indexedDB.deleteDatabase("concept-book-db");
    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error);
    request.onblocked = () => resolve();
  });

const cardInput = (overrides: Partial<ContextCardInput> = {}): ContextCardInput => ({
  ...createEmptyContextCardInput(),
  title: "カード",
  domainTags: ["情報"],
  keyConcepts: "A, B, C",
  ...overrides
});

describe("indexeddb context card + concept sync atomicity (#200)", () => {
  let storage: IndexedDBStorage;
  let contextStorage: ContextCardIndexedDBStorage;

  beforeEach(async () => {
    await deleteDb();
    storage = new IndexedDBStorage();
    contextStorage = new ContextCardIndexedDBStorage();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("全成功: Card 1件と Concept A/B/C を同一 commit する", async () => {
    const result = await storage.saveContextCardWithConceptSync({
      mode: "create",
      input: cardInput({ keyConcepts: "A, B, C" })
    });

    expect(result.createdCount).toBe(3);
    expect(result.updatedCount).toBe(0);

    const cards = await contextStorage.getAllContextCards();
    const concepts = await storage.getAllConcepts();
    expect(cards).toHaveLength(1);
    expect(cards[0]?.id).toBe(result.card.id);
    expect(concepts).toHaveLength(3);
    expect(concepts.map((c) => c.title).sort()).toEqual(["A", "B", "C"]);
    for (const concept of concepts) {
      expect(concept.sourceContextCardId).toBe(result.card.id);
      expect(concept.autoGenerated).toBe(true);
      expect(concept.sourceContextCardTermKey).toBe(concept.title.toLowerCase());
    }
  });

  it("1件目 Concept create failure では Card も Concept も残らない", async () => {
    const originalAdd = IDBObjectStore.prototype.add;
    vi.spyOn(IDBObjectStore.prototype, "add").mockImplementation(function (
      this: IDBObjectStore,
      value,
      key
    ) {
      if (this.name === "concepts") {
        throw new Error("injected first concept add failure");
      }
      return originalAdd.call(this, value, key);
    });

    await expect(
      storage.saveContextCardWithConceptSync({
        mode: "create",
        input: cardInput({ keyConcepts: "A, B, C" })
      })
    ).rejects.toThrow("injected first concept add failure");

    expect(await storage.getAllConcepts()).toHaveLength(0);
    expect(await contextStorage.getAllContextCards()).toHaveLength(0);
  });

  it("3件中2件目 create failure では先行 A も含めて全rollback", async () => {
    let conceptAdds = 0;
    const originalAdd = IDBObjectStore.prototype.add;
    vi.spyOn(IDBObjectStore.prototype, "add").mockImplementation(function (
      this: IDBObjectStore,
      value,
      key
    ) {
      if (this.name === "concepts") {
        conceptAdds += 1;
        if (conceptAdds === 2) {
          throw new Error("injected second concept add failure");
        }
      }
      return originalAdd.call(this, value, key);
    });

    await expect(
      storage.saveContextCardWithConceptSync({
        mode: "create",
        input: cardInput({ keyConcepts: "A, B, C" })
      })
    ).rejects.toThrow("injected second concept add failure");

    expect(await storage.getAllConcepts()).toHaveLength(0);
    expect(await contextStorage.getAllContextCards()).toHaveLength(0);
  });

  it("create 後の update failure でも Card / 新規Concept / 既存Concept をrollback", async () => {
    const existing = await storage.createConcept({
      ...createEmptyConceptInput(),
      title: "X",
      domainTags: ["情報"]
    });

    const originalPut = IDBObjectStore.prototype.put;
    vi.spyOn(IDBObjectStore.prototype, "put").mockImplementation(function (
      this: IDBObjectStore,
      value,
      key
    ) {
      if (
        this.name === "concepts" &&
        value &&
        typeof value === "object" &&
        "id" in value &&
        (value as { id: string }).id === existing.id
      ) {
        throw new Error("injected concept update failure");
      }
      return originalPut.call(this, value, key);
    });

    await expect(
      storage.saveContextCardWithConceptSync({
        mode: "create",
        input: cardInput({ keyConcepts: "NewA, X", domainTags: ["教育"] })
      })
    ).rejects.toThrow("injected concept update failure");

    expect(await contextStorage.getAllContextCards()).toHaveLength(0);
    const concepts = await storage.getAllConcepts();
    expect(concepts).toHaveLength(1);
    expect(concepts[0]?.id).toBe(existing.id);
    expect(concepts[0]?.title).toBe("X");
    expect(concepts[0]?.domainTags).toEqual(["情報"]);
  });

  it("edit の Concept create failure では Card update もrollback", async () => {
    const created = await storage.saveContextCardWithConceptSync({
      mode: "create",
      input: cardInput({ title: "old", keyConcepts: "A" })
    });

    const originalAdd = IDBObjectStore.prototype.add;
    vi.spyOn(IDBObjectStore.prototype, "add").mockImplementation(function (
      this: IDBObjectStore,
      value,
      key
    ) {
      if (this.name === "concepts") {
        throw new Error("injected B create failure");
      }
      return originalAdd.call(this, value, key);
    });

    await expect(
      storage.saveContextCardWithConceptSync({
        mode: "edit",
        contextCardId: created.card.id,
        input: cardInput({ title: "new", keyConcepts: "B" })
      })
    ).rejects.toThrow("injected B create failure");

    const cards = await contextStorage.getAllContextCards();
    expect(cards).toHaveLength(1);
    expect(cards[0]?.title).toBe("old");
    expect(cards[0]?.keyConcepts).toBe("A");
    const concepts = await storage.getAllConcepts();
    expect(concepts.map((c) => c.title)).toEqual(["A"]);
    expect(concepts.find((c) => c.title === "B")).toBeUndefined();
  });

  it("全同期失敗では成功件数を返さず Card も commit しない", async () => {
    const originalAdd = IDBObjectStore.prototype.add;
    vi.spyOn(IDBObjectStore.prototype, "add").mockImplementation(function (
      this: IDBObjectStore,
      value,
      key
    ) {
      if (this.name === "concepts") {
        throw new Error("injected all sync failure");
      }
      return originalAdd.call(this, value, key);
    });

    await expect(
      storage.saveContextCardWithConceptSync({
        mode: "create",
        input: cardInput({ keyConcepts: "A, B, C" })
      })
    ).rejects.toThrow("injected all sync failure");

    expect(await contextStorage.getAllContextCards()).toHaveLength(0);
    expect(await storage.getAllConcepts()).toHaveLength(0);
  });

  it("failure 解除後の retry で duplicate を作らない", async () => {
    const originalAdd = IDBObjectStore.prototype.add;
    const spy = vi.spyOn(IDBObjectStore.prototype, "add").mockImplementation(function (
      this: IDBObjectStore,
      value,
      key
    ) {
      if (this.name === "concepts") {
        throw new Error("injected retry failure");
      }
      return originalAdd.call(this, value, key);
    });

    await expect(
      storage.saveContextCardWithConceptSync({
        mode: "create",
        input: cardInput({ keyConcepts: "A, B, C" })
      })
    ).rejects.toThrow("injected retry failure");

    spy.mockRestore();

    const result = await storage.saveContextCardWithConceptSync({
      mode: "create",
      input: cardInput({ keyConcepts: "A, B, C" })
    });

    const cards = await contextStorage.getAllContextCards();
    const concepts = await storage.getAllConcepts();
    expect(cards).toHaveLength(1);
    expect(cards[0]?.id).toBe(result.card.id);
    expect(concepts).toHaveLength(3);
    expect(concepts.map((c) => c.title).sort()).toEqual(["A", "B", "C"]);
  });

  it("transaction 内の fresh Concept 集合から plan を計算する", async () => {
    await storage.createConcept({
      ...createEmptyConceptInput(),
      title: "AI",
      domainTags: ["情報"]
    });

    const result = await storage.saveContextCardWithConceptSync({
      mode: "create",
      input: cardInput({ keyConcepts: "AI", domainTags: ["教育"] })
    });

    const concepts = await storage.getAllConcepts();
    expect(result.createdCount).toBe(0);
    expect(result.updatedCount).toBe(1);
    expect(concepts).toHaveLength(1);
    expect(concepts[0]?.title).toBe("AI");
    expect(concepts[0]?.domainTags).toEqual(["情報", "教育"]);
  });

  it("#194 rename 後も provenance で既存 Concept を解決する", async () => {
    const created = await storage.saveContextCardWithConceptSync({
      mode: "create",
      input: cardInput({ keyConcepts: "AI" })
    });
    const original = (await storage.getAllConcepts())[0];
    expect(original).toBeDefined();
    await storage.updateConcept(original!.id, { title: "人工知能" });

    const edited = await storage.saveContextCardWithConceptSync({
      mode: "edit",
      contextCardId: created.card.id,
      input: cardInput({ keyConcepts: "AI" })
    });

    const concepts = await storage.getAllConcepts();
    expect(edited.createdCount).toBe(0);
    expect(concepts).toHaveLength(1);
    expect(concepts[0]?.id).toBe(original!.id);
    expect(concepts[0]?.title).toBe("人工知能");
    expect(concepts[0]?.sourceContextCardId).toBe(created.card.id);
    expect(concepts[0]?.sourceContextCardTermKey).toBe("ai");
  });

  it("#195 同名 ambiguous では Card を保存し Concept は変更しない", async () => {
    await storage.createConcept({ ...createEmptyConceptInput(), title: "AI", domainTags: ["情報"] });
    await storage.createConcept({ ...createEmptyConceptInput(), title: "AI", domainTags: ["哲学"] });

    const result = await storage.saveContextCardWithConceptSync({
      mode: "create",
      input: cardInput({ keyConcepts: "AI", domainTags: ["教育"] })
    });

    const cards = await contextStorage.getAllContextCards();
    const concepts = await storage.getAllConcepts();
    expect(result.createdCount).toBe(0);
    expect(result.updatedCount).toBe(0);
    expect(cards).toHaveLength(1);
    expect(concepts).toHaveLength(2);
    expect(concepts.every((c) => c.title === "AI")).toBe(true);
    expect(concepts.map((c) => [...c.domainTags].sort())).toEqual(
      expect.arrayContaining([
        ["情報"],
        ["哲学"]
      ])
    );
    expect(concepts.every((c) => !c.domainTags.includes("教育"))).toBe(true);
  });

  it("duplicate exact provenance は ambiguous として Concept を変更しない", async () => {
    const created = await storage.saveContextCardWithConceptSync({
      mode: "create",
      input: cardInput({ keyConcepts: "AI" })
    });
    const first = (await storage.getAllConcepts())[0]!;
    await storage.createConcept({
      ...createEmptyConceptInput(),
      title: "人工知能",
      sourceContextCardId: created.card.id,
      autoGenerated: true,
      sourceContextCardTermKey: "ai"
    });

    const edited = await storage.saveContextCardWithConceptSync({
      mode: "edit",
      contextCardId: created.card.id,
      input: cardInput({ title: "updated", keyConcepts: "AI", domainTags: ["教育"] })
    });

    const cards = await contextStorage.getAllContextCards();
    const concepts = await storage.getAllConcepts();
    expect(cards[0]?.title).toBe("updated");
    expect(edited.createdCount).toBe(0);
    expect(edited.updatedCount).toBe(0);
    expect(concepts).toHaveLength(2);
    expect(concepts.find((c) => c.id === first.id)?.title).toBe("AI");
    expect(concepts.every((c) => !c.domainTags.includes("教育"))).toBe(true);
  });
});
